[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
opacity = 0.7

[window.padding]
x = 10
y = 4


# Spawn a new terminal window
[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
