[font]
size = 12.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[window]
opacity = 0.9

[window.padding]
x = 10
y = 4

[colors.primary]
background = "#171421"
foreground = "#7ED510"

[colors.normal]
green = "#7ED510"
blue = "#1574BB"

[colors.bright]
green = "#7ED510"

# Spawn a new terminal window
[keyboard]
bindings = [
  { key = "N", mods = "Control|Shift", action = "CreateNewWindow" }
]
